/* =========================  • ANALYTICS & COMPETENCY PRO =========================
   Verified Secure Exam competency is aggregated into studentStatsV19 so the teacher
   dashboard can render Chapter → Lesson → Knowledge Code → NB/TH/VD without loading
   full submissions. Practice/self-reported progress remains clearly separated.
   ================================================================================ */
const V31_ANALYTICS_SCHEMA=31;
let v31LastClassData=null;

function v31SafeKey(v=''){return String(v||'').replace(/[^A-Za-z0-9_-]/g,c=>'_'+c.charCodeAt(0).toString(16)+'_')||'_'}
function v31Clamp01(v){v=Number(v);return Number.isFinite(v)?Math.max(0,Math.min(1,v)):0}
function v31KnowledgeMeta(code=''){return (typeof allKnowledgeCodes==='function'?allKnowledgeCodes():[]).find(x=>x.code===code)||null}
function v31Level(v=''){v=String(v||'').toUpperCase();return ['NB','TH','VD'].includes(v)?v:'OTHER'}
function v31ResolvedResult(r={}){let meta=v31KnowledgeMeta(r.knowledgeCode||'')||{},code=r.knowledgeCode||'',lessonId=r.lessonId||meta.lessonId||'',chapterId=Number(r.chapterId||meta.chapterId)||0,level=v31Level(r.level||meta.level||'');return {...r,code,lessonId,chapterId,level,title:meta.title||code,credit:v31Clamp01(r.credit),correct:!!r.correct}}
function v31CompetencyNumeric(rows=[]){return (rows||[]).map(v31ResolvedResult).filter(r=>r.code)}
function v31AddBucket(map,key,meta,r,sign=1){if(!key)return;let x=map[key]||(map[key]={...meta,attempts:0,credit:0,correct:0});x.attempts+=sign;x.credit+=sign*r.credit;x.correct+=sign*(r.correct?1:0)}
function v31AggregateResults(rows=[]){
  const out={schemaVersion:31,totalAttempts:0,totalCredit:0,totalCorrect:0,codes:{},lessons:{},chapters:{},levels:{}};
  v31CompetencyNumeric(rows).forEach(r=>{out.totalAttempts++;out.totalCredit+=r.credit;out.totalCorrect+=r.correct?1:0;v31AddBucket(out.codes,v31SafeKey(r.code),{code:r.code,title:r.title,lessonId:r.lessonId,chapterId:r.chapterId,level:r.level},r);v31AddBucket(out.lessons,v31SafeKey(r.lessonId),{lessonId:r.lessonId,chapterId:r.chapterId},r);v31AddBucket(out.chapters,String(r.chapterId),{chapterId:r.chapterId},r);v31AddBucket(out.levels,r.level,{level:r.level},r)});return out
}
function v31StudentStatsDeltaPayload(rows=[],sign=1){
  if(!firebase?.firestore?.FieldValue)return {};
  const inc=firebase.firestore.FieldValue.increment,agg=v31AggregateResults(rows),obj={schemaVersion:31,totalAttempts:inc(sign*agg.totalAttempts),totalCredit:inc(sign*agg.totalCredit),totalCorrect:inc(sign*agg.totalCorrect),updatedAt:firebaseServerTimestamp(),codes:{},lessons:{},chapters:{},levels:{}};
  for(const [k,x] of Object.entries(agg.codes))obj.codes[k]={code:x.code,title:x.title||x.code,lessonId:x.lessonId||'',chapterId:Number(x.chapterId)||0,level:x.level||'',attempts:inc(sign*x.attempts),credit:inc(sign*x.credit),correct:inc(sign*x.correct)};
  for(const [k,x] of Object.entries(agg.lessons))obj.lessons[k]={lessonId:x.lessonId||'',chapterId:Number(x.chapterId)||0,attempts:inc(sign*x.attempts),credit:inc(sign*x.credit),correct:inc(sign*x.correct)};
  for(const [k,x] of Object.entries(agg.chapters))obj.chapters[k]={chapterId:Number(x.chapterId)||0,attempts:inc(sign*x.attempts),credit:inc(sign*x.credit),correct:inc(sign*x.correct)};
  for(const [k,x] of Object.entries(agg.levels))obj.levels[k]={level:x.level||k,attempts:inc(sign*x.attempts),credit:inc(sign*x.credit),correct:inc(sign*x.correct)};
  return {verifiedCompetencyV31:obj,verifiedCompetencySchemaVersion:31}
}
function v31NormalizeStoredCompetency(x={}){let out={schemaVersion:Number(x.schemaVersion)||31,totalAttempts:Math.max(0,Number(x.totalAttempts)||0),totalCredit:Math.max(0,Number(x.totalCredit)||0),totalCorrect:Math.max(0,Number(x.totalCorrect)||0),codes:{},lessons:{},chapters:{},levels:{}};for(const part of ['codes','lessons','chapters','levels'])for(const [k,v] of Object.entries(x?.[part]||{})){let attempts=Math.max(0,Number(v?.attempts)||0),credit=Math.max(0,Number(v?.credit)||0),correct=Math.max(0,Number(v?.correct)||0);if(attempts>0)out[part][k]={...v,attempts,credit,correct,accuracy:credit/attempts}}out.accuracy=out.totalAttempts?out.totalCredit/out.totalAttempts:null;return out}
function v31MergeStoredCompetencies(list=[]){let out={schemaVersion:31,totalAttempts:0,totalCredit:0,totalCorrect:0,codes:{},lessons:{},chapters:{},levels:{}};for(const raw of list){let c=v31NormalizeStoredCompetency(raw||{});out.totalAttempts+=c.totalAttempts;out.totalCredit+=c.totalCredit;out.totalCorrect+=c.totalCorrect;for(const part of ['codes','lessons','chapters','levels'])for(const [k,x] of Object.entries(c[part]||{})){let y=out[part][k]||(out[part][k]={...x,attempts:0,credit:0,correct:0,students:0});y.attempts+=x.attempts;y.credit+=x.credit;y.correct+=x.correct;y.students+=1;y.accuracy=y.attempts?y.credit/y.attempts:null}}out.accuracy=out.totalAttempts?out.totalCredit/out.totalAttempts:null;return out}
function v31State(acc,attempts){if(!attempts||attempts<2)return 'new';if(acc<.6)return 'weak';if(acc<.8)return 'reinforce';return 'strong'}
function v31Pct(v){return v==null?'—':Math.round(Number(v)*100)+'%'}

/* ---------- Aggregate official Secure Exam results once ---------- */
async function v31AggregateOfficialRows(classId,assignmentId,rows=[]){
  let pending=(rows||[]).filter(x=>x&&x.score!=null&&Array.isArray(x.questionResults)&&x.questionResults.length&&!x.competencyV31Aggregated);if(!pending.length)return 0;
  for(let i=0;i<pending.length;i+=80){let b=firebaseDb.batch();pending.slice(i,i+80).forEach(x=>{let uid=x.uid||x.id||'';if(!uid)return;let stats={uid,classId,name:x.name||'',email:x.email||'',schemaVersion:31,updatedAt:firebaseServerTimestamp(),...v31StudentStatsDeltaPayload(x.questionResults,1)};b.set(firebaseStudentStatsRef(classId).doc(uid),stats,{merge:true});b.set(firebaseAssignmentsRef(classId).doc(assignmentId).collection('submissions').doc(uid),{competencyV31Aggregated:true,competencyV31SchemaVersion:31,competencyV31AggregatedAt:firebaseServerTimestamp()},{merge:true});x.competencyV31Aggregated=true});await b.commit()}
  firebaseV19InvalidateClass(classId);return pending.length
}
const v31OldGradePending=typeof firebaseGradePendingSubmissionDocs==='function'?firebaseGradePendingSubmissionDocs:null;
if(v31OldGradePending)firebaseGradePendingSubmissionDocs=async function(classId,assignmentId,a,sDocs){let rows=await v31OldGradePending(classId,assignmentId,a,sDocs);try{await v31AggregateOfficialRows(classId,assignmentId,rows)}catch(err){console.warn(' competency aggregate',err)}return rows};

/*  retry removes the previous official competency contribution before the next attempt. */
firebaseResetSubmission=async function(classId,assignmentId,uid){
  if(!requireTeacher('Cấp thêm lượt làm'))return;
  try{let aRef=firebaseAssignmentsRef(classId).doc(assignmentId),subRef=aRef.collection('submissions').doc(uid),idxRef=firebaseSubmissionIndexRef(classId).doc(firebaseSubmissionIndexId(assignmentId,uid)),[aSnap,sSnap,iSnap]=await Promise.all([aRef.get(),subRef.get(),idxRef.get()]);if(!aSnap.exists)return alert('Bài giao không còn tồn tại.');if(!sSnap.exists&&!iSnap.exists)return alert('Học sinh chưa có lượt nộp để cấp lại.');let a=aSnap.data()||{},d=sSnap.exists?sSnap.data():(iSnap.data()||{}),idx=iSnap.exists?iSnap.data():{},n=Math.max(v27AttemptNumber(d),v27AttemptNumber(idx)),oldMax=v27MaxAttempts(a),newMax=Math.max(oldMax,n+1);if(n>=5&&oldMax>=5)return alert(' đang giới hạn tối đa 5 lượt cho một bài. Học sinh này đã dùng đủ 5 lượt.');newMax=Math.min(5,newMax);if(!confirm(`Cấp thêm lượt ${n+1}/${newMax} cho ${d.name||d.email||uid}? Điểm và năng lực xác minh của lượt hiện tại sẽ được gỡ khỏi thống kê chính thức; lịch sử lượt vẫn được giữ.`))return;if(typeof v26StoreSubmissionRecoveryBundle==='function')await v26StoreSubmissionRecoveryBundle(classId,assignmentId,uid);let retryIndex={uid,name:d.name||idx.name||'',email:d.email||idx.email||'',classId,assignmentId,assignmentTitle:d.assignmentTitle||idx.assignmentTitle||a.title||'',attemptId:d.attemptId||idx.attemptId||'',attemptNumber:n,answered:Number(d.answered??idx.answered)||0,total:Number(d.total??idx.total)||Number(a.questionCount)||0,durationMs:Number(d.durationMs??idx.durationMs)||0,violations:Number(d.violations??idx.violations)||0,status:'retry',secureSchemaVersion:FIREBASE_SECURE_SCHEMA,indexSchemaVersion:19,submittedAt:d.submittedAt||idx.submittedAt||firebaseServerTimestamp()},b=firebaseDb.batch();if(sSnap.exists)b.delete(subRef);b.set(idxRef,retryIndex,{merge:false});if(newMax!==oldMax)b.set(aRef,{maxAttempts:newMax,updatedAt:firebaseServerTimestamp()},{merge:true});if(d.score!=null){let score=Number(d.score)||0,stats={gradedCount:firebase.firestore.FieldValue.increment(-1),scoreSum:firebase.firestore.FieldValue.increment(-score),gradedAssignmentIds:firebase.firestore.FieldValue.arrayRemove(assignmentId),updatedAt:firebaseServerTimestamp()};if(d.competencyV31Aggregated&&Array.isArray(d.questionResults))Object.assign(stats,v31StudentStatsDeltaPayload(d.questionResults,-1));b.set(aRef,{gradedCount:firebase.firestore.FieldValue.increment(-1),scoreSum:firebase.firestore.FieldValue.increment(-score),updatedAt:firebaseServerTimestamp()},{merge:true});b.set(firebaseStudentStatsRef(classId).doc(uid),stats,{merge:true})}await b.commit();await firebaseAuditLog('assignment.retry.grant.v31',{classId,assignmentId,uid,previousAttempt:n,maxAttempts:newMax});firebaseV19InvalidateClass(classId);closeModal();await firebaseShowAssignmentResults(classId,assignmentId)}catch(err){alert(firebaseErrorText(err))}
};

/* Rare destructive path, but keep official competency exact when an assignment is purged. */
firebasePurgeAssignment=async function(classId,assignmentId){
  if(!requireTeacher('Xóa vĩnh viễn bài giao'))return;let ref=firebaseAssignmentsRef(classId).doc(assignmentId);try{let aSnap=await ref.get();if(!aSnap.exists)return alert('Bài giao không còn tồn tại.');let a=aSnap.data()||{};if(a.status!=='trashed')return alert(' chỉ cho xóa vĩnh viễn bài đang ở Thùng rác.');let token=prompt(`Xóa vĩnh viễn “${a.title||'Bài giao'}” cùng lượt nộp?\n\nNhập XOA để xác nhận:`);if(String(token||'').trim().toUpperCase()!=='XOA')return;if(typeof v26StoreAssignmentRecoveryBundle==='function')await v26StoreAssignmentRecoveryBundle(classId,assignmentId);let [subs,idx,attempts,drafts]=await Promise.all([ref.collection('submissions').get(),firebaseSubmissionIndexRef(classId).where('assignmentId','==',assignmentId).get(),ref.collection('attemptHistoryV27').get(),ref.collection('draftsV30').get()]);for(let i=0;i<subs.docs.length;i+=90){let b=firebaseDb.batch();subs.docs.slice(i,i+90).forEach(d=>{let x=d.data()||{};b.delete(d.ref);if(x.score!=null){let score=Number(x.score)||0,stats={gradedCount:firebase.firestore.FieldValue.increment(-1),scoreSum:firebase.firestore.FieldValue.increment(-score),gradedAssignmentIds:firebase.firestore.FieldValue.arrayRemove(assignmentId),updatedAt:firebaseServerTimestamp()};if(x.competencyV31Aggregated&&Array.isArray(x.questionResults))Object.assign(stats,v31StudentStatsDeltaPayload(x.questionResults,-1));b.set(firebaseStudentStatsRef(classId).doc(d.id),stats,{merge:true})}});await b.commit()}for(const snap of [idx,attempts,drafts])for(let i=0;i<snap.docs.length;i+=350){let b=firebaseDb.batch();snap.docs.slice(i,i+350).forEach(d=>b.delete(d.ref));await b.commit()}let b=firebaseDb.batch();b.delete(ref);b.delete(firebaseAnswerKeysRef(classId).doc(assignmentId));await b.commit();await firebaseAuditLog('assignment.purge.v31',{classId,assignmentId,title:a.title||'',submissionCount:subs.size});firebaseV19InvalidateClass(classId);closeModal();await firebaseRefreshAssignments();alert('Đã xóa vĩnh viễn.  đã đồng thời gỡ phần năng lực xác minh của bài khỏi thống kê chính thức.')}catch(err){alert(firebaseErrorText(err))}
};

async function v31BackfillClassCompetency(classId){
  if(!requireTeacher('Chuẩn hóa năng lực xác minh '))return;if(!classId)return alert('Hãy chọn lớp.');if(!confirm(' sẽ đọc các submission đã chấm của lớp để bổ sung năng lực xác minh cho dữ liệu  trở về trước. Đây là thao tác một lần và có phát sinh Reads. Tiếp tục?'))return;
  let scanned=0,added=0;try{let assignments=await firebaseV19LoadAssignments(classId,true);for(const row of assignments){let aid=row.id,s=await firebaseAssignmentsRef(classId).doc(aid).collection('submissions').get();scanned+=s.size;let rows=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.score!=null&&Array.isArray(x.questionResults)&&x.questionResults.length&&!x.competencyV31Aggregated);if(rows.length)added+=await v31AggregateOfficialRows(classId,aid,rows)}await firebaseDb.collection('classes').doc(classId).set({competencyV31Ready:true,competencyV31BackfillAt:firebaseServerTimestamp()},{merge:true});await firebaseAuditLog('analytics.competency.backfill.v31',{classId,scanned,added});firebaseTeacherDashboardCache=null;await firebaseRefreshTeacherDashboard(true);alert(`Đã chuẩn hóa : quét ${scanned} bài nộp, bổ sung ${added} lượt chấm vào bản đồ năng lực xác minh.`)}catch(err){alert(firebaseErrorText(err))}
}

/* ---------- Low-read class intelligence: reuse studentStatsV19 ---------- */
const v31OldBuildTeacherData=typeof firebaseBuildTeacherDashboardData==='function'?firebaseBuildTeacherDashboardData:null;
if(v31OldBuildTeacherData)firebaseBuildTeacherDashboardData=function(args={}){let c=v31OldBuildTeacherData(args),sm=new Map((args.studentStats||[]).map(x=>[x.id,x.data||x]));c.students.forEach(s=>{let st=sm.get(s.uid)||{};s.verifiedCompetencyV31=v31NormalizeStoredCompetency(st.verifiedCompetencyV31||{})});c.verifiedCompetencyV31=v31MergeStoredCompetencies(c.students.map(s=>s.verifiedCompetencyV31));c.verifiedCompetencyEvidence=c.verifiedCompetencyV31.totalAttempts;c.verifiedCompetencyAccuracy=c.verifiedCompetencyV31.accuracy;c.verifiedCompetencyCoverage=Object.values(c.verifiedCompetencyV31.codes||{}).filter(x=>x.attempts>=2).length;return c};

function v31CodeRows(c){let meta=typeof allKnowledgeCodes==='function'?allKnowledgeCodes():[],map=new Map(Object.values(c?.verifiedCompetencyV31?.codes||{}).map(x=>[x.code,x]));return meta.map((m,i)=>{let x=map.get(m.code)||{},attempts=Number(x.attempts)||0,credit=Number(x.credit)||0,accuracy=attempts?credit/attempts:null;return {...m,order:i,attempts,credit,accuracy,correct:Number(x.correct)||0,students:Number(x.students)||0,state:v31State(accuracy,attempts)}})}
function v31ChapterRows(c){let comp=c?.verifiedCompetencyV31||{},map=comp.chapters||{};return chapters.map(ch=>{let x=map[String(ch.id)]||{},attempts=Number(x.attempts)||0,accuracy=attempts?Number(x.credit||0)/attempts:null;return {id:ch.id,title:ch.title,attempts,accuracy,state:v31State(accuracy,attempts)}})}
function v31LessonRows(c,chapterId=0){let comp=c?.verifiedCompetencyV31||{},map=comp.lessons||{};return chapters.filter(ch=>!chapterId||ch.id===chapterId).flatMap(ch=>ch.lessons.map(l=>{let x=Object.values(map).find(v=>v.lessonId===l.id)||{},attempts=Number(x.attempts)||0,accuracy=attempts?Number(x.credit||0)/attempts:null;return {id:l.id,title:l.common,chapterId:ch.id,attempts,accuracy,state:v31State(accuracy,attempts)}}))}
function v31LevelRows(c){let map=c?.verifiedCompetencyV31?.levels||{};return ['NB','TH','VD'].map(level=>{let x=map[level]||{},attempts=Number(x.attempts)||0,accuracy=attempts?Number(x.credit||0)/attempts:null;return {level,attempts,accuracy,state:v31State(accuracy,attempts)}})}
function v31BarClass(acc,attempts){return v31State(acc,attempts)}
function v31RenderHierarchy(c){let box=document.getElementById('v31CompetencyHierarchy');if(!box)return;let codes=v31CodeRows(c),lessons=v31LessonRows(c),weakest=v31ChapterRows(c).filter(x=>x.attempts).sort((a,b)=>(a.accuracy??1)-(b.accuracy??1))[0]?.id;box.innerHTML=chapters.map(ch=>{let cr=v31ChapterRows(c).find(x=>x.id===ch.id),p=cr?.accuracy==null?0:Math.round(cr.accuracy*100),lessonHtml=ch.lessons.map(l=>{let lr=lessons.find(x=>x.id===l.id),lp=lr?.accuracy==null?0:Math.round(lr.accuracy*100),codeHtml=codes.filter(x=>x.lessonId===l.id).map(k=>`<button class="v31-code ${k.state}" onclick="v31OpenVerifiedCode('${attrEsc(k.code)}')"><span><b>${esc(k.code)}</b><small>${esc(k.title)}</small></span><strong>${v31Pct(k.accuracy)}</strong><em>${k.attempts} câu</em></button>`).join('');return `<div class="v31-lesson"><div class="v31-lesson-head"><div><b>${esc(l.id)} • ${esc(l.common)}</b><small>${lr?.attempts||0} câu xác minh</small></div><span>${v31Pct(lr?.accuracy)}</span></div><div class="v31-progress"><i class="${v31BarClass(lr?.accuracy,lr?.attempts)}" style="width:${lp}%"></i></div><div class="v31-codes">${codeHtml}</div></div>`}).join('');return `<details class="v31-chapter" ${ch.id===weakest?'open':''}><summary><div><b>Chương ${ch.id}. ${esc(ch.title)}</b><small>${cr?.attempts||0} câu xác minh</small></div><div class="v31-summary-score ${cr?.state||'new'}">${v31Pct(cr?.accuracy)}</div></summary><div class="v31-progress"><i class="${v31BarClass(cr?.accuracy,cr?.attempts)}" style="width:${p}%"></i></div>${lessonHtml}</details>`}).join('')}
function v31RenderStudentMatrix(c){let box=document.getElementById('v31StudentMatrix');if(!box)return;let weak=v31CodeRows(c).filter(x=>x.attempts>=2).sort((a,b)=>(a.accuracy??1)-(b.accuracy??1)||b.attempts-a.attempts).slice(0,6);if(!weak.length){box.innerHTML='<div class="teacher-live-empty">Chưa có đủ điểm câu xác minh. Mở “Kết quả” các bài đã chấm hoặc dùng nút “Chuẩn hóa dữ liệu ”.</div>';return}let head=weak.map(k=>`<th title="${attrEsc(k.title)}">${esc(k.code)}</th>`).join(''),rows=(c.students||[]).map(s=>{let cmap=new Map(Object.values(s.verifiedCompetencyV31?.codes||{}).map(x=>[x.code,x]));return `<tr><td><button class="link-btn" onclick="v31OpenStudentCompetency('${attrEsc(s.uid)}')"><b>${esc(s.name)}</b></button></td>${weak.map(k=>{let x=cmap.get(k.code),a=x?.attempts?Number(x.credit||0)/Number(x.attempts):null;return `<td><span class="v31-cell ${v31State(a,Number(x?.attempts)||0)}">${v31Pct(a)}<small>${Number(x?.attempts)||0}</small></span></td>`}).join('')}</tr>`}).join('');box.innerHTML=`<div class="table-wrap"><table class="table v31-matrix"><thead><tr><th>Học sinh</th>${head}</tr></thead><tbody>${rows}</tbody></table></div>`}
/* Prefer verified Secure Exam evidence when suggesting teacher remediation. */
const v31OldRenderSuggestions=typeof v22RenderSuggestions==='function'?v22RenderSuggestions:null;
v22RenderSuggestions=function(c){
  const box=document.getElementById('v22AssignmentSuggestions');if(!box)return;
  const skills=v31CodeRows(c).filter(x=>x.attempts>=2&&x.accuracy<.8).sort((a,b)=>(a.accuracy??1)-(b.accuracy??1)||b.attempts-a.attempts).slice(0,3);
  if(!skills.length){if(v31OldRenderSuggestions)return v31OldRenderSuggestions(c);box.innerHTML='<div class="teacher-live-empty">Chưa có đủ dữ liệu xác minh để đề xuất bài củng cố.</div>';return}
  box.innerHTML=`<div class="v22-suggestions">${skills.map((x,i)=>{let mode=x.accuracy<.6?'support':'developing',pool=typeof v22SuggestionPool==='function'?v22SuggestionPool(x.code):[],label=mode==='support'?'Nhóm cần hỗ trợ':'Nhóm đang củng cố';return `<div class="v22-suggestion"><div class="v22-suggestion-rank">${i+1}</div><div><b>${esc(x.code)} • ${esc(x.title)}</b><small>Verified ${Math.round(x.accuracy*100)}% • ${x.attempts} câu đã chấm • ngân hàng ghép được ${pool.length} câu</small></div><button class="btn btn-blue" ${pool.length?'':'disabled'} onclick="v22PrepareSuggestedAssignment('${attrEsc(c.classId)}','${attrEsc(x.code)}','${mode}')">Tạo đề → ${label}</button></div>`}).join('')}</div><div class="v22-data-note"><b>:</b> ưu tiên mã yếu từ Secure Exam đã chấm. Giáo viên vẫn xem lại đề và đối tượng trước khi bấm “Giao bài”.</div>`;
};

function v31RenderTeacherCompetency(c){v31LastClassData=c;let comp=c?.verifiedCompetencyV31||{},codes=v31CodeRows(c),tested=codes.filter(x=>x.attempts>=2),weak=tested.filter(x=>x.accuracy<.6),levels=v31LevelRows(c),set=(id,v)=>{let e=document.getElementById(id);if(e)e.textContent=v};set('v31MetricEvidence',comp.totalAttempts||0);set('v31MetricAccuracy',v31Pct(comp.accuracy));set('v31MetricCoverage',`${tested.length}/${codes.length}`);set('v31MetricWeak',weak.length);let lbox=document.getElementById('v31LevelSummary');if(lbox)lbox.innerHTML=levels.map(x=>`<div class="v31-level ${x.state}"><b>${x.level==='NB'?'Nhận biết':x.level==='TH'?'Thông hiểu':'Vận dụng'}</b><strong>${v31Pct(x.accuracy)}</strong><small>${x.attempts} câu xác minh</small><div class="v31-progress"><i class="${x.state}" style="width:${x.accuracy==null?0:Math.round(x.accuracy*100)}%"></i></div></div>`).join('');let note=document.getElementById('v31VerifiedNote');if(note)note.innerHTML=comp.totalAttempts?`<b>✓ Dữ liệu xác minh:</b> ${comp.totalAttempts} kết quả câu từ Secure Exam đã được giáo viên chấm. Dashboard không đọc toàn bộ submission để dựng bản đồ này.`:'<b>Chưa có năng lực xác minh .</b> Các bài chấm mới sẽ tự tích lũy. Với dữ liệu  cũ, dùng “Chuẩn hóa dữ liệu ” một lần.';v31RenderHierarchy(c);v31RenderStudentMatrix(c)}

function v31OpenVerifiedCode(code){if(!v31LastClassData)return;let c=v31LastClassData,meta=v31KnowledgeMeta(code)||{code,title:code},rows=(c.students||[]).map(s=>{let x=Object.values(s.verifiedCompetencyV31?.codes||{}).find(v=>v.code===code),attempts=Number(x?.attempts)||0,accuracy=attempts?Number(x.credit||0)/attempts:null;return {s,attempts,accuracy}}).filter(x=>x.attempts).sort((a,b)=>(a.accuracy??1)-(b.accuracy??1)),html=rows.map(x=>`<div class="smart-preview-row"><div><b>${esc(x.s.name)}</b><br><small>${x.attempts} câu xác minh</small></div><span class="skill-state ${v31State(x.accuracy,x.attempts)}">${v31Pct(x.accuracy)}</span></div>`).join('');openModal(`${code} • ${meta.title||code}`,`${rows.length} học sinh có bằng chứng xác minh`,`<div class="firebase-banner"><b> Verified:</b> chỉ dùng câu từ Secure Exam đã được giáo viên chấm.</div><div class="smart-preview-list mt">${html||'<div class="notification-empty">Chưa có dữ liệu xác minh cho mã này.</div>'}</div>`,`<button class="btn btn-soft" onclick="closeModal()">Đóng</button>${typeof v22PrepareSuggestedAssignment==='function'?`<button class="btn btn-blue" onclick="closeModal();v22PrepareSuggestedAssignment('${attrEsc(c.classId)}','${attrEsc(code)}','support')">Tạo bài củng cố</button>`:''}`)}
function v31OpenStudentCompetency(uid){if(!v31LastClassData)return;let c=v31LastClassData,s=(c.students||[]).find(x=>x.uid===uid);if(!s)return;let vc=s.verifiedCompetencyV31||{},chaptersRows=chapters.map(ch=>{let x=vc.chapters?.[String(ch.id)]||{},n=Number(x.attempts)||0,a=n?Number(x.credit||0)/n:null;return {id:ch.id,title:ch.title,n,a}}),codes=Object.values(vc.codes||{}).filter(x=>Number(x.attempts)>0).map(x=>({...x,accuracy:Number(x.credit||0)/Math.max(1,Number(x.attempts)||0)})).sort((a,b)=>a.accuracy-b.accuracy),practice=(s.progress?.skillSnapshot||[]).slice().sort((a,b)=>(a.accuracy??1)-(b.accuracy??1)).slice(0,8),chap=chaptersRows.map(x=>`<div class="v31-student-chapter"><span>Ch.${x.id} • ${esc(x.title)}</span><b>${v31Pct(x.a)}</b><small>${x.n} câu</small></div>`).join(''),codeHtml=codes.slice(0,12).map(x=>`<div class="smart-preview-row"><div><b>${esc(x.code)} • ${esc(x.title||'')}</b><br><small>${x.attempts} câu xác minh • ${esc(x.level||'')}</small></div><span class="skill-state ${v31State(x.accuracy,x.attempts)}">${v31Pct(x.accuracy)}</span></div>`).join(''),practiceHtml=practice.map(x=>`<span class="pill ${Number(x.accuracy)<.6?'tag-red':'tag-yellow'}">${esc(x.code)} ${Math.round(Number(x.accuracy||0)*100)}%</span>`).join(' ')||'Chưa có dữ liệu tự luyện';openModal(`Năng lực • ${s.name}`,`${c.className} • Verified + Practice tách nguồn`,`<div class="grid grid-4"><div class="card"><small>Điểm TB xác minh</small><h2>${s.avgScore==null?'—':s.avgScore.toFixed(2)}</h2></div><div class="card"><small>Câu xác minh</small><h2>${vc.totalAttempts||0}</h2></div><div class="card"><small>Độ chính xác xác minh</small><h2>${v31Pct(vc.accuracy)}</h2></div><div class="card"><small>Tự luyện</small><h2>${s.practiceAccuracy==null?'—':Math.round(s.practiceAccuracy*100)+'%'}</h2></div></div><div class="card mt"><h3 style="margin-top:0">Theo chương • xác minh</h3><div class="v31-student-chapters">${chap}</div></div><div class="card mt"><h3 style="margin-top:0">Mã kiến thức • xác minh</h3><div class="smart-preview-list">${codeHtml||'<div class="notification-empty">Chưa có câu xác minh theo mã.</div>'}</div></div><div class="card mt"><h3 style="margin-top:0">Điểm yếu tự luyện • tham khảo</h3><div>${practiceHtml}</div></div>`,`<button class="btn btn-soft" onclick="closeModal()">Đóng</button>`)}

/* ---------- Class comparison snapshot  ---------- */
const v31OldClassSummary=typeof v22ClassSummary==='function'?v22ClassSummary:null;
v22ClassSummary=function(c){let base=v31OldClassSummary?v31OldClassSummary(c):{},comp=c?.verifiedCompetencyV31||{},tested=v31CodeRows(c).filter(x=>x.attempts>=2),top=tested.filter(x=>x.accuracy<.8).sort((a,b)=>(a.accuracy??1)-(b.accuracy??1)||b.attempts-a.attempts)[0];return {...base,schemaVersion:31,verifiedEvidence:Number(comp.totalAttempts)||0,verifiedAccuracy:comp.accuracy==null?null:+Number(comp.accuracy).toFixed(4),verifiedCoverage:tested.length,weakVerifiedCode:top?.code||'',weakVerifiedAccuracy:top?.accuracy==null?null:+Number(top.accuracy).toFixed(4),capturedAt:new Date().toISOString()}};
v22PersistClassSummary=async function(c){if(!firebaseUser||!firebaseDb||!isTeacherRole?.()||!c?.classId)return;let summary=v22ClassSummary(c),owned=(firebaseOwnedClasses||[]).find(x=>x.id===c.classId),old=owned?.analyticsV31||owned?.analyticsV30||owned?.analyticsV29||owned?.analyticsV28||owned?.analyticsV27||owned?.analyticsV26||owned?.analyticsV25||owned?.analyticsV24||owned?.analyticsV23||owned?.analyticsV22||null,signature=JSON.stringify({m:summary.memberCount,a:summary.assignmentCount,c:summary.completionRate,s:summary.averageScore,h:summary.needsHelp,ve:summary.verifiedEvidence,va:summary.verifiedAccuracy,vc:summary.verifiedCoverage,w:summary.weakVerifiedCode}),oldSig=old?JSON.stringify({m:old.memberCount,a:old.assignmentCount,c:old.completionRate,s:old.averageScore,h:old.needsHelp,ve:old.verifiedEvidence,va:old.verifiedAccuracy,vc:old.verifiedCoverage,w:old.weakVerifiedCode}):'';if(old&&oldSig===signature)return;let now=Date.now(),last=v22SummaryWriteAt.get(c.classId)||0;if(now-last<V22_CLASS_SUMMARY_MIN_WRITE_MS)return;v22SummaryWriteAt.set(c.classId,now);try{await firebaseDb.collection('classes').doc(c.classId).set({analyticsV31:{...summary,updatedAt:firebaseServerTimestamp()}},{merge:true});if(owned)owned.analyticsV31=summary;v22RenderClassComparison(c)}catch(err){console.warn(' class summary',err)}};
v22RenderClassComparison=function(c){let box=document.getElementById('v22ClassComparison');if(!box)return;let rows=(firebaseOwnedClasses||[]).map(cls=>{let summary=cls.id===c.classId?v22ClassSummary(c):cls.analyticsV31||cls.analyticsV30||cls.analyticsV29||cls.analyticsV28||cls.analyticsV27||cls.analyticsV26||cls.analyticsV25||cls.analyticsV24||cls.analyticsV23||cls.analyticsV22||null;return {id:cls.id,name:cls.name||'Lớp học',summary,current:cls.id===c.classId}}).sort((a,b)=>(b.summary?.averageScore??-1)-(a.summary?.averageScore??-1));box.innerHTML=rows.length?`<div class="v22-compare-table">${rows.map((x,i)=>`<div class="v22-compare-row ${x.current?'current':''}"><span>${i+1}</span><div><b>${esc(x.name)}</b><small>${x.summary?`${x.summary.memberCount||0} HS • nộp ${x.summary.completionRate==null?'—':Math.round(x.summary.completionRate*100)+'%'} • ${x.summary.verifiedEvidence||0} câu xác minh`:'Chưa có snapshot'}</small></div><strong>${x.summary?.averageScore==null?'—':Number(x.summary.averageScore).toFixed(2)}</strong><em>${x.summary?.verifiedAccuracy==null?'—':Math.round(Number(x.summary.verifiedAccuracy)*100)+'%'}</em></div>`).join('')}</div><div class="v22-data-note">Cột cuối: độ chính xác năng lực xác minh . Lớp khác chỉ đọc snapshot trên document lớp, không tải học sinh.</div>`:'<div class="teacher-live-empty">Chưa có lớp để so sánh.</div>'};

/* ---------- Student source trust panel ---------- */
function v31HistorySummary(rows=[]){let out={total:0,credit:0,chapters:{},levels:{NB:{n:0,c:0},TH:{n:0,c:0},VD:{n:0,c:0}}};(rows||[]).forEach(h=>{let r=v31ResolvedResult(h);if(!r.code)return;out.total++;out.credit+=r.credit;let ch=out.chapters[r.chapterId]||(out.chapters[r.chapterId]={n:0,c:0});ch.n++;ch.c+=r.credit;if(out.levels[r.level]){out.levels[r.level].n++;out.levels[r.level].c+=r.credit}});out.accuracy=out.total?out.credit/out.total:null;return out}
function v31RenderStudentTrust(){let box=document.getElementById('v31StudentTrust');if(!box||typeof analyticsHistory!=='function')return;let h=analyticsHistory(),verified=h.filter(x=>String(x.mode||'').startsWith('assignment')),practice=h.filter(x=>!String(x.mode||'').startsWith('assignment')),v=v31HistorySummary(verified),p=v31HistorySummary(practice),levels=['NB','TH','VD'].map(k=>{let x=v.levels[k];return `<span><b>${k}</b> ${x.n?v31Pct(x.c/x.n):'—'} <small>(${x.n})</small></span>`}).join('');box.innerHTML=`<div class="v31-source-card verified"><div><b>✓ Secure Exam đã xác minh</b><strong>${v31Pct(v.accuracy)}</strong><small>${v.total} kết quả câu</small></div><div class="v31-source-levels">${levels}</div></div><div class="v31-source-card practice"><div><b>◎ Tự luyện trên thiết bị</b><strong>${v31Pct(p.accuracy)}</strong><small>${p.total} kết quả câu</small></div><div class="v31-source-note">Dùng để cá nhân hóa luyện tập; không thay điểm bài giáo viên chấm.</div></div>`}
const v31OldRenderAnalytics=typeof renderAnalytics==='function'?renderAnalytics:null;
if(v31OldRenderAnalytics)renderAnalytics=function(){let r=v31OldRenderAnalytics();v31RenderStudentTrust();return r};

/* Render after existing teacher dashboard has populated its normal cards. */
const v31OldRenderTeacherDashboardCache=typeof renderTeacherDashboardCache==='function'?renderTeacherDashboardCache:null;
if(v31OldRenderTeacherDashboardCache)renderTeacherDashboardCache=function(c){let r=v31OldRenderTeacherDashboardCache(c);v31RenderTeacherCompetency(c);return r};
const v31OldLoadClassIntelligence=typeof firebaseLoadClassIntelligence==='function'?firebaseLoadClassIntelligence:null;
if(v31OldLoadClassIntelligence)firebaseLoadClassIntelligence=async function(classId,force=false){let c=await v31OldLoadClassIntelligence(classId,force);if(c&&!c.verifiedCompetencyV31){/* cache built before  override in a rare hot-reload path */ firebaseTeacherDashboardCache=null;c=await v31OldLoadClassIntelligence(classId,true)}return c};

console.info('Math12 Hub  Analytics & Competency Pro loaded');
