/* =========================================================
   Math12 Hub  — Missions + Achievements
   - Daily/weekly missions are derived from real attempt history.
   - Claims are idempotent by period + mission key.
   - Achievements unlock once and may grant exclusive cosmetics.
   ========================================================= */
(function(){
'use strict';const BUILD='38.1-missions-achievements',SCHEMA=381,uid=()=>firebaseUser?.uid||'local',now=()=>new Date().toISOString();
const dayKey=()=>v379Economy.dayKey(new Date());function weekKey(d=new Date()){let x=new Date(d),day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return v379Economy.dayKey(x)}
const missions=[
{id:'daily-q10',period:'day',label:'Làm 10 câu hôm nay',kind:'questions',target:10,xp:30,gold:50},
{id:'daily-c5',period:'day',label:'Đúng 5 câu hôm nay',kind:'correct',target:5,xp:20,gold:30},
{id:'daily-a1',period:'day',label:'Hoàn thành 1 bài luyện/đề',kind:'attempts',target:1,xp:25,gold:40},
{id:'week-q50',period:'week',label:'Làm 50 câu trong tuần',kind:'questions',target:50,xp:150,gold:250},
{id:'week-a3',period:'week',label:'Hoàn thành 3 bài luyện/đề',kind:'attempts',target:3,xp:100,gold:150}
];
const achievements=[
{id:'first-exam',label:'Bước chân đầu tiên',desc:'Hoàn thành bài luyện/đề đầu tiên.',check:s=>s.allAttempts>=1,xp:30,gold:50},
{id:'perfect-10',label:'Perfect 10',desc:'Đạt 10 điểm một bài được chấm.',check:s=>s.best>=9.95,xp:100,gold:150,item:'acc-perfect-crown'},
{id:'correct-100',label:'Trăm câu chính xác',desc:'Tích lũy 100 câu đúng hoàn toàn.',check:s=>s.allCorrect>=100,xp:200,gold:300},
{id:'streak-7',label:'Bền bỉ 7 ngày',desc:'Duy trì chuỗi học ít nhất 7 ngày.',check:s=>s.streak>=7,xp:120,gold:180,item:'bg-streak7'}
];
function blank(owner=uid()){return {schemaVersion:SCHEMA,ownerUid:owner,claimed:{},achievements:{},updatedAt:''}}
function sanitize(raw,owner=uid()){let x=raw&&typeof raw==='object'?JSON.parse(JSON.stringify(raw)):blank(owner);x.schemaVersion=SCHEMA;x.ownerUid=owner;x.claimed=x.claimed&&typeof x.claimed==='object'?x.claimed:{};x.achievements=x.achievements&&typeof x.achievements==='object'?x.achievements:{};x.updatedAt=String(x.updatedAt||'');return x}
function bucket(){state.missionsV381ByUser=state.missionsV381ByUser&&typeof state.missionsV381ByUser==='object'?state.missionsV381ByUser:{};return state.missionsV381ByUser}function profile(){return sanitize(bucket()[uid()]||blank(uid()),uid())}
function persist(p,{cloud=true}={}){p=sanitize(p,uid());p.updatedAt=now();bucket()[uid()]=p;try{save({sync:false,reason:'missions-v38.1'})}catch(_){};if(cloud&&firebaseUser&&firebaseDb&&!firebaseAccountLocked)firebaseDb.collection('users').doc(firebaseUser.uid).set({missionsV381:p,updatedAt:firebaseServerTimestamp()},{merge:true}).then(()=>{firebaseProfile={...(firebaseProfile||{}),missionsV381:p}}).catch(err=>console.warn(' sync',err));render();return p}
function adoptCloud(){let c=firebaseProfile?.missionsV381;if(!c)return;let l=profile(),cloud=sanitize(c,uid());if((Date.parse(cloud.updatedAt||0)||0)>=(Date.parse(l.updatedAt||0)||0)){bucket()[uid()]=cloud;try{save({sync:false,reason:'missions-cloud-v38.1'})}catch(_){}}render()}
function allAttempts(){return (state.examAttempts||[]).filter(a=>a&&a.mode!=='assignment'&&Number.isFinite(Number(a.score)))}
function periodRows(period){let start;if(period==='day'){let d=new Date();d.setHours(0,0,0,0);start=d.getTime()}else{let d=new Date(),day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);d.setHours(0,0,0,0);start=d.getTime()}let aa=allAttempts().filter(a=>(Date.parse(a.date||0)||0)>=start),q=aa.flatMap(a=>a.questionResults||[]);return {attempts:aa.length,questions:q.length,correct:q.filter(x=>x.correct).length}}
function stats(){let a=allAttempts(),q=a.flatMap(x=>x.questionResults||[]),scores=a.map(x=>Number(x.score)).filter(Number.isFinite);return {allAttempts:a.length,allQuestions:q.length,allCorrect:q.filter(x=>x.correct).length,best:scores.length?Math.max(...scores):0,streak:typeof learningStreakDays==='function'?learningStreakDays():0}}
function missionState(m){let r=periodRows(m.period),v=Math.min(m.target,Number(r[m.kind])||0),period=m.period==='day'?dayKey():weekKey();let key=`${period}:${m.id}`;return {...m,value:v,complete:v>=m.target,claimed:!!profile().claimed[key],claimKey:key}}
function claim(id){let m=missions.find(x=>x.id===id);if(!m)return;let st=missionState(m);if(!st.complete){examToast?.('Nhiệm vụ chưa hoàn thành.');return}if(st.claimed){examToast?.('Phần thưởng này đã nhận.');return}let p=profile();p.claimed[st.claimKey]=now();persist(p);v379Economy.grant({xp:m.xp,gold:m.gold,key:`mission:${st.claimKey}`,source:`mission:${m.id}`});examToast?.(`✓ Nhiệm vụ: +${m.xp} EXP • +${m.gold} vàng`);render()}
function checkAchievements(){let s=stats(),p=profile(),newOnes=[];for(const a of achievements){if(p.achievements[a.id]||!a.check(s))continue;p.achievements[a.id]={at:now(),label:a.label};newOnes.push(a)}if(!newOnes.length)return;persist(p);for(const a of newOnes){v379Economy.grant({xp:a.xp,gold:a.gold,key:`achievement:${a.id}`,source:`achievement:${a.id}`});if(a.item)v380Shop.grantItem(a.item,`achievement:${a.id}`);examToast?.(`🏆 Thành tích: ${a.label}`)}render()}
function missionCard(m){let s=missionState(m),pct=Math.round(s.value*100/s.target);return `<article class="v381-mission ${s.complete?'complete':''}"><div><b>${esc(m.label)}</b><small>${m.period==='day'?'Nhiệm vụ ngày':'Nhiệm vụ tuần'} • +${m.xp} EXP • +${m.gold} 🪙</small><i><em style="width:${pct}%"></em></i><span>${s.value}/${m.target}</span></div><button class="btn ${s.complete&&!s.claimed?'btn-blue':'btn-soft'}" ${!s.complete||s.claimed?'disabled':''} onclick="v381Missions.claim('${m.id}')">${s.claimed?'✓ Đã nhận':s.complete?'Nhận thưởng':'Đang làm'}</button></article>`}
function achievementCard(a){let u=profile().achievements[a.id];return `<article class="v381-achievement ${u?'unlocked':''}"><span>${u?'🏆':'🔒'}</span><div><b>${esc(a.label)}</b><small>${esc(a.desc)}${a.item?`Vật phẩm độc quyền`:''}</small></div><em>${u?'Đã mở khóa':'Chưa đạt'}</em></article>`}
function render(){let root=document.getElementById('v381MissionPage');if(!root)return;checkAchievementsSafe();root.innerHTML=`<div class="v381-hero"><div><span>QUEST BOARD</span><h2>Nhiệm vụ & Thành tích</h2><p>Phần thưởng đến từ hoạt động học thật. Không có quay thưởng ngẫu nhiên và không mua lợi thế điểm số.</p></div><div><b>🔥 ${typeof learningStreakDays==='function'?learningStreakDays():0}</b><small>ngày liên tục</small></div></div><div class="grid grid-2 mt"><div class="card"><h3>Nhiệm vụ ngày</h3>${missions.filter(x=>x.period==='day').map(missionCard).join('')}</div><div class="card"><h3>Nhiệm vụ tuần</h3>${missions.filter(x=>x.period==='week').map(missionCard).join('')}</div></div><div class="card mt"><h3>Thành tích</h3><div class="v381-achievements">${achievements.map(achievementCard).join('')}</div></div>`}
let checking=false;function checkAchievementsSafe(){if(checking)return;checking=true;try{let s=stats(),p=profile(),todo=achievements.filter(a=>!p.achievements[a.id]&&a.check(s));if(todo.length)setTimeout(checkAchievements,0)}finally{checking=false}}
function inject(){try{ROLE_ACCESS.student.add('missions')}catch(_){};let nav=document.querySelector('[data-nav-group="student-achievement"] .nav-group-items');if(nav&&!nav.querySelector('[data-page="missions"]'))nav.insertAdjacentHTML('beforeend','<button data-page="missions" title="Nhiệm vụ & Thành tích"><span class="ico">🏆</span><span class="nav-label">Nhiệm vụ</span></button>');let main=document.querySelector('main .content')||document.querySelector('main');if(main&&!document.getElementById('page-missions'))main.insertAdjacentHTML('beforeend','<section class="section student-only" id="page-missions"><div id="v381MissionPage"></div></section>')}
function install(){inject();if(typeof window.goPage==='function'&&!window.goPage.__v381){let base=window.goPage;let wrap=function(page,internal=false){let r=base(page,internal);if(page==='missions')requestAnimationFrame(render);return r};wrap.__v381=true;window.goPage=wrap}if(typeof window.firebaseHydrateUser==='function'&&!window.firebaseHydrateUser.__v381){let base=window.firebaseHydrateUser;let wrap=async function(u){let r=await base(u);adoptCloud();checkAchievements();return r};wrap.__v381=true;window.firebaseHydrateUser=wrap}window.addEventListener('math12hub:attempt-rewarded',()=>{checkAchievements();render()});window.addEventListener('math12hub:state-saved',()=>{if(document.getElementById('page-missions')?.classList.contains('active'))render()});setTimeout(()=>{checkAchievements();render()},350)}
window.v381Missions={build:BUILD,schema:SCHEMA,missions,achievements,profile,missionState,claim,stats,checkAchievements,render};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
