/* =========================================================
   Math12 Hub V38.6 — Mega Shop
   120+ cosmetic items, filters, rarity, owned inventory, wardrobe bridge.
   Cosmetic only: never changes scores, answers, difficulty or mastery.
   ========================================================= */
(function(){
'use strict';
const BUILD='38.6-mega-shop',SCHEMA=386;
const uid=()=>window.firebaseUser?.uid||'local', now=()=>new Date().toISOString();
const catalog=[];let filterSlot='all',filterRarity='all',sortMode='level',searchText='';
const colors=[
 ['Navy','#24436F'],['Sky','#4F86E8'],['Mint','#35A879'],['Violet','#7654C8'],['Rose','#D45A82'],['Amber','#D99B26'],['Slate','#4A596E'],['Aqua','#258FA8'],['Crimson','#B6424A'],['Pearl','#E9EEF7']
];
const rarityBy=i=>i<4?'common':i<7?'rare':i<9?'epic':'legendary';
const priceBy=(i,base=180)=>Math.round((base+i*115)*(rarityBy(i)==='legendary'?2.1:rarityBy(i)==='epic'?1.55:rarityBy(i)==='rare'?1.2:1)/10)*10;
const levelBy=i=>1+i*2;
function add(it){if(!it?.id||catalog.some(x=>x.id===it.id))return;catalog.push({...it})}
function wardrobeSeries(slot,prefix,label,icon,props){colors.forEach(([name,color],i)=>add({id:`${prefix}-${i+1}`,slot,label:`${label} ${name}`,icon,color,rarity:rarityBy(i),price:priceBy(i,props.base||180),level:levelBy(i),shop:true,...(props.make?.(i,color)||{})}))}
wardrobeSeries('hair','hair-v386','Tóc', '💇',{base:150,make:(i,color)=>({hairStyle:['short','side','spiky','bob','pony','long'][i%6],hairColor:color})});
wardrobeSeries('top','top-v386','Áo Math', '👕',{base:220,make:(i,color)=>({color,accent:colors[(i+3)%colors.length][1]})});
wardrobeSeries('bottom','bottom-v386','Quần/Váy', '👖',{base:190,make:(i,color)=>({color})});
wardrobeSeries('shoes','shoes-v386','Sneaker', '👟',{base:170,make:(i,color)=>({color})});
wardrobeSeries('head','head-v386','Mũ học giả', '🎓',{base:240,make:(i,color)=>({color,shape:i>=8?'crown':'cap'})});
wardrobeSeries('glasses','glasses-v386','Kính', '👓',{base:160,make:(i,color)=>({color})});
wardrobeSeries('back','back-v386','Ba lô', '🎒',{base:230,make:(i,color)=>({color})});
wardrobeSeries('hand','hand-v386','Dụng cụ', '📐',{base:200,make:(i,color)=>({color,tool:['compass','book','calculator','ruler'][i%4]})});
const specialGroups=[
 ['pet','pet-v386','Pet', '🐾',['Mèo Pi','Cú Euler','Cáo Gauss','Robot Newton','Thỏ Fibonacci','Rồng Vector','Gấu Sigma','Chim Delta','Slime Integral','Drone Oxyz']],
 ['aura','aura-v386','Aura','✨',['Tia số','Đạo hàm','Tích phân','Vector','Oxyz','Xác suất','Ma trận','Vũ trụ π','Hàm số','Legend 10']],
 ['background','bg-v386','Nền','🖼',['Lớp học','Thư viện','Bảng đen','Lưới Oxyz','Phòng Lab','Vũ trụ Toán','Đấu trường','Sân trường','Đêm sao','Phòng Champion']],
 ['emote','emote-v386','Emote','🕺',['Vẫy tay','Suy nghĩ','Yes!','Perfect 10','Nhảy Level Up','Cúi chào','High Five','Victory','Spin','Champion']]
];
specialGroups.forEach(([slot,prefix,label,icon,names])=>names.forEach((name,i)=>add({id:`${prefix}-${i+1}`,slot,label:`${label}: ${name}`,icon,color:colors[i][1],rarity:rarityBy(i),price:priceBy(i,300),level:levelBy(i)+2,shop:true,variant:i+1})));
// Achievement-only showcase items; V38.8 will grant them.
[
 ['head-perfect-10','head','Vương miện Perfect 10','♛','#FFD65A'],['aura-streak-7','aura','Hào quang Streak 7','✦','#F3B63E'],['back-master-function','back','Áo choàng Master Hàm số','🎓','#3556A8'],['pet-master-derivative','pet','Pet Đạo hàm','🐉','#7654C8']
].forEach(([id,slot,label,icon,color])=>add({id,slot,label,icon,color,rarity:'legendary',price:null,level:1,shop:false,exclusive:true}));
const wardrobeItems=catalog.filter(x=>['hair','top','bottom','shoes','head','glasses','back','hand'].includes(x.slot));
function blank(){return {schemaVersion:SCHEMA,ownerUid:uid(),owned:[],equipped:{pet:'',aura:'',background:'',emote:''},purchases:[],updatedAt:''}}
function bucket(){window.state.megaShopV386ByUser=window.state.megaShopV386ByUser&&typeof window.state.megaShopV386ByUser==='object'?window.state.megaShopV386ByUser:{};return window.state.megaShopV386ByUser}
function profile(){const raw=bucket()[uid()]||blank();return {...blank(),...raw,ownerUid:uid(),owned:[...new Set(Array.isArray(raw.owned)?raw.owned:[])],equipped:{...blank().equipped,...(raw.equipped||{})},purchases:Array.isArray(raw.purchases)?raw.purchases.slice(-500):[]}}
function persist(p,{cloud=true}={}){p={...p,schemaVersion:SCHEMA,ownerUid:uid(),updatedAt:now()};bucket()[uid()]=p;try{window.save?.({sync:false,reason:'mega-shop-v38.6'})}catch(_){};if(cloud&&window.firebaseUser&&window.firebaseDb&&!window.firebaseAccountLocked){window.firebaseDb.collection('users').doc(window.firebaseUser.uid).set({megaShopV386:p,updatedAt:window.firebaseServerTimestamp?.()},{merge:true}).catch(e=>console.warn('V38.6 shop sync',e))}render();return p}
function item(id){return catalog.find(x=>x.id===id)||null}
function owned(id){return profile().owned.includes(id)||!!window.v380Shop?.owned?.(id)}
function equipped(id){const it=item(id);if(!it)return false;if(['hair','top','bottom','shoes','head','glasses','back','hand'].includes(it.slot))return window.v385Wardrobe?.profile?.().equipped?.[it.slot]===id;return profile().equipped[it.slot]===id}
function buy(id){const it=item(id);if(!it||it.shop===false)return false;if(owned(id)){equip(id);return true}const eco=window.v379Economy?.profile?.()||{level:1,gold:0};if(eco.level<(it.level||1)){window.examToast?.(`Cần Lv.${it.level} để mua ${it.label}`);return false}const pay=window.v379Economy?.spendGold?.(it.price||0,`mega-shop:${id}`);if(!pay?.ok){window.examToast?.(`Chưa đủ vàng • cần thêm ${pay?.need||it.price} 🪙`);return false}const p=profile();p.owned.push(id);p.purchases.push({id,price:it.price,at:now()});persist(p);equip(id);window.examToast?.(`✓ Đã mua ${it.label}`);return true}
function grantItem(id,source='achievement'){const it=item(id);if(!it)return false;const p=profile();if(!p.owned.includes(id)){p.owned.push(id);p.purchases.push({id,price:0,source,at:now()});persist(p)}return true}
function equip(id){const it=item(id);if(!it||!owned(id))return false;if(['hair','top','bottom','shoes','head','glasses','back','hand'].includes(it.slot)){window.v385Wardrobe?.equip?.(id)}else{const p=profile();p.equipped[it.slot]=p.equipped[it.slot]===id?'':id;persist(p);window.v384Avatar3D?.rebuild?.()}render();return true}
function adoptCloud(){const c=window.firebaseProfile?.megaShopV386;if(!c)return;const l=profile(),ct=Date.parse(c.updatedAt||0)||0,lt=Date.parse(l.updatedAt||0)||0;if(ct>=lt){bucket()[uid()]={...blank(),...c,ownerUid:uid()};try{window.save?.({sync:false,reason:'mega-shop-cloud-v38.6'})}catch(_){}}}
function slotLabel(s){return {all:'Tất cả',hair:'Tóc',top:'Áo',bottom:'Quần/Váy',shoes:'Giày',head:'Mũ',glasses:'Kính',back:'Ba lô',hand:'Cầm tay',pet:'Pet',aura:'Aura',background:'Nền',emote:'Emote'}[s]||s}
function card(it,eco){const has=owned(it.id),eq=equipped(it.id),locked=eco.level<(it.level||1),canBuy=it.shop!==false&&!locked;const price=it.shop===false?'Thành tích':`${Number(it.price||0).toLocaleString('vi-VN')} 🪙`;return `<article class="v386-card ${locked&&!has?'locked':''} ${eq?'equipped':''}"><div class="v386-preview" style="--swatch:${it.color||'#315bc7'}"><span class="v386-rarity ${it.rarity}">${String(it.rarity||'common').toUpperCase()}</span><i>${it.icon||'✦'}</i></div><h4>${window.esc?.(it.label)||it.label}</h4><div class="v386-meta"><span>${slotLabel(it.slot)}</span><span>Lv.${it.level||1}</span>${it.exclusive?'<span>Độc quyền</span>':''}</div><div class="v386-price ${it.shop===false?'free':''}">${price}</div>${has?`<button class="${eq?'soft':''}" onclick="v386MegaShop.equip('${it.id}')">${eq?'✓ Đang dùng':'Trang bị'}</button>`:`<button ${canBuy?'':'disabled'} onclick="v386MegaShop.buy('${it.id}')">${it.shop===false?'Mở bằng thành tích':locked?`Cần Lv.${it.level}`:'Mua ngay'}</button>`}</article>`}
function render(){const root=document.getElementById('v380ShopPage');if(!root)return;const eco=window.v379Economy?.profile?.()||{gold:0,level:1};let list=catalog.filter(it=>(filterSlot==='all'||it.slot===filterSlot)&&(filterRarity==='all'||it.rarity===filterRarity)&&(!searchText||it.label.toLowerCase().includes(searchText.toLowerCase())));list.sort((a,b)=>sortMode==='price'?(a.price??999999)-(b.price??999999):sortMode==='rarity'?['common','rare','epic','legendary'].indexOf(a.rarity)-['common','rare','epic','legendary'].indexOf(b.rarity):(a.level||1)-(b.level||1));const p=profile();root.innerHTML=`<div class="v386-shop"><div class="v386-hero"><div><div class="v386-kicker">V38.6 • MEGA COSMETIC SHOP</div><h2>Math Avatar Mega Shop</h2><p>${catalog.length} vật phẩm cosmetic. Mua bằng vàng học tập, không có vật phẩm pay-to-win và không món nào thay đổi điểm số.</p></div><div class="v386-wallet"><small>SỐ DƯ HỌC TẬP</small><b>🪙 ${Number(eco.gold||0).toLocaleString('vi-VN')}</b><span>Lv.${eco.level||1} • ${p.owned.length} món Mega Shop</span></div></div><div class="v386-toolbar"><input class="v386-search" value="${window.esc?.(searchText)||searchText}" placeholder="Tìm vật phẩm…" oninput="v386MegaShop.search(this.value)"><select class="v386-select" onchange="v386MegaShop.setRarity(this.value)"><option value="all" ${filterRarity==='all'?'selected':''}>Mọi độ hiếm</option><option value="common" ${filterRarity==='common'?'selected':''}>Common</option><option value="rare" ${filterRarity==='rare'?'selected':''}>Rare</option><option value="epic" ${filterRarity==='epic'?'selected':''}>Epic</option><option value="legendary" ${filterRarity==='legendary'?'selected':''}>Legendary</option></select><select class="v386-select" onchange="v386MegaShop.setSort(this.value)"><option value="level" ${sortMode==='level'?'selected':''}>Theo level</option><option value="price" ${sortMode==='price'?'selected':''}>Theo giá</option><option value="rarity" ${sortMode==='rarity'?'selected':''}>Theo độ hiếm</option></select></div><div class="v386-cats">${['all','hair','top','bottom','shoes','head','glasses','back','hand','pet','aura','background','emote'].map(s=>`<button class="${filterSlot===s?'active':''}" onclick="v386MegaShop.setSlot('${s}')">${slotLabel(s)}</button>`).join('')}</div><div class="v386-summary"><span>Hiển thị <b>${list.length}</b> / ${catalog.length} vật phẩm</span><span>Common → Rare → Epic → Legendary</span></div><div class="v386-grid">${list.length?list.map(it=>card(it,eco)).join(''):'<div class="v386-empty">Không tìm thấy vật phẩm phù hợp.</div>'}</div><div class="v386-collection-bar"><div class="v386-stat"><small>Tổng catalog</small><b>${catalog.length}</b></div><div class="v386-stat"><small>Đã sở hữu</small><b>${p.owned.length}</b></div><div class="v386-stat"><small>Legendary</small><b>${catalog.filter(x=>x.rarity==='legendary').length}</b></div><div class="v386-stat"><small>Nhóm vật phẩm</small><b>12</b></div></div></div>`}
function setSlot(x){filterSlot=x;render()}function setRarity(x){filterRarity=x;render()}function setSort(x){sortMode=x;render()}function search(x){searchText=String(x||'');render()}
function install(){window.v385Wardrobe?.registerItems?.(wardrobeItems);if(typeof window.goPage==='function'&&!window.goPage.__v386){const base=window.goPage;const wrap=function(page,internal=false){const r=base(page,internal);if(page==='shop')requestAnimationFrame(render);return r};wrap.__v386=true;window.goPage=wrap}if(typeof window.firebaseHydrateUser==='function'&&!window.firebaseHydrateUser.__v386){const base=window.firebaseHydrateUser;const wrap=async function(u){const r=await base(u);adoptCloud();return r};wrap.__v386=true;window.firebaseHydrateUser=wrap}window.addEventListener('math12hub:game-reward',()=>requestAnimationFrame(render));if(document.getElementById('page-shop')?.classList.contains('active'))render()}
window.v386MegaShop={build:BUILD,schema:SCHEMA,catalog,profile,item,owned,equipped,buy,equip,grantItem,render,setSlot,setRarity,setSort,search,adoptCloud};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
